variables:
  server_ip: 8.130.116.36
  upload_path: /home/SE3
  password: 940926698xiAOL

# 定义执行的各个阶段及顺序
stages:
  - build
  - upload
  - deploy


vue-build:
  stage: build
  image: node:latest
  script:
    - cd vue
    - npm install
    - npm run build
  cache:
    paths:
     - vue/node_modules/
     - vue/dist/
  artifacts:
    paths: 
      - vue/dist


# 上传生成的 dist到你的应用服务器，这里使用 ictu/sshpass 这个镜像，是为了使用 sshpass 命令

upload-jar:
  stage: upload
  image: ictu/sshpass
  script: 
    - sshpass -p $ssh_password scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no vue/dist root@$server_ip:$upload_path

# 启动 vue
deploy-test:
  stage: deploy
  image: ictu/sshpass
  script:
    - sshpass -p $ssh_password ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$server_ip "nginx -s reload >/dev/null 2>&1 &"
